### ISSUE TITLE
When will this be completed by

### ISSUE THREAD

**Issue by ghost** [thelucyclub/Pets#11]
Great plugin, but id love to know when the ToDo list will be completed and this amazing plugin will be working.. thanks!

**Comment by thelucyclub** [comment]
Soon. Check out the current forks they may be a little bit more updated.

**Comment by thelucyclub** [comment]
Actually, when I feel like comitting and pushing updates.

**Comment by thelucyclub** [comment]
I HAD a seperate very updated and good version with built-in Mob AI but it got lost in the infamous recycle bin.

**Comment by matthew4444** [comment]
use slapper plugin code for spawningwolf with nametag

**Comment by matthew4444** [comment]
https://github.com/PMPlugins/Slapper use file restoring software also

**Comment by matthew4444** [comment]
np

**Comment by matthew4444** [comment]
i started this plugin so lets finish it soon

**Comment by matthew4444** [comment]
i almost frogot to say use the enityfollow tag or something like that in mob ai

**Comment by matthew4444** [comment]
i ment enitiyfollow event instead of tag

**Comment by matthew4444** [comment]
and use a bit of minecart with chestcode in it to but u need to porgram its ai also,and i have another plugin idea after this one

**Comment by matthew4444** [comment]
u dont need to use minecart ai if u dont want to by the way

**Comment by thelucyclub** [comment]
If you are not going to help, please don't post useless issues. This is an issues report, not a forum.
