### ISSUE TITLE
Disown command error

### ISSUE THREAD

**Issue by ClockProgramming** [thelucyclub/Pets#26]
[18:59:24] [Server thread/CRITICAL]: Unhandled exception executing command 'pet disown Test' in pet: Call to a member function close() on integer
[18:59:24] [Server thread/CRITICAL]: Error: "Call to a member function close() on integer" (EXCEPTION) in "/Pets-php7/src/Pets/Pets" at line 68

**Comment by jasonwynn10** [comment]
I figured that would happen...

**Comment by GlitchPlayer** [comment]
Then can you try to make like pets disappearing instead?

**Comment by jasonwynn10** [comment]
what do you mean?

**Comment by Vietnamese02** [comment]
Link plugin pet-php7 ?

**Comment by jasonwynn10** [comment]
no idea what you are saying

**Comment by jasonwynn10** [comment]
or asking

**Comment by GlitchPlayer** [comment]
like when you type disown command, the pet will disappear.

**Comment by GlitchPlayer** [comment]
@Vietnamese02 Find the master button then a popup will show showing php7

**Comment by jasonwynn10** [comment]
@GlitchPlayer look at the most recent version of the plugin, it should work...

**Comment by GlitchPlayer** [comment]
K
