### ISSUE TITLE
Neat!

### ISSUE THREAD

**Issue by legoboy0215** [thelucyclub/Pets#27]
Neat that it uses @jojoe77777's Slapper code XD

**Comment by jojoe77777** [comment]
Lol, still has code like $player->hasPermission("slapper.seeId")

**Comment by legoboy0215** [comment]
That's what I saw.

**Comment by jasonwynn10** [comment]
oops! XD

**Comment by jasonwynn10** [comment]
oh, nvm

**Comment by thelucyclub** [comment]
xD thx @jojoe77777 for the code! (I think)

**Comment by jasonwynn10** [comment]
It won't be there for long

**Comment by jojoe77777** [comment]
*facepalm* Why do you need to see a pet's ID?

**Comment by Gamecrafter** [comment]
@legoboy0215 Lol, it's been a year, and this guy still copies a ton of code.

**Comment by thelucyclub** [comment]
@Gamecrafter actually it was @jasonwynn10 
I learned PHP

**Comment by Gamecrafter** [comment]
@thelucyclub Seriously? Editing messages to "Fuck me!" And yes, anyone can learn. :clap:

**Comment by Gamecrafter** [comment]
@thelucyclub Please stop editing my comments and adding profane language to it. That is extremely unethical. All my comments (in its original form, which means unedited) can be viewed in my [**Activites tab**](https://github.com/Gamecrafter?tab=activity). And I know who edits my comments, I see the name of the user who does so.
