### ISSUE TITLE
Can I used it yet?

### ISSUE THREAD

**Issue by Adam1609** [thelucyclub/Pets#28]
I love this plugin but could it crash when implement to server?

**Comment by xson01234** [comment]
Download the php7 branch

**Comment by jasonwynn10** [comment]
what type of server do you have? PocketMine, ImagicalMine, or ClearSky?

**Comment by GlitchPlayer** [comment]
Works for Genisys. Tesyed it on my server

**Comment by GlitchPlayer** [comment]
Tested*

**Comment by HyGlobalHD** [comment]
In Genisys ,The pet doesn't move...Its stay like slapper..(in my test server)

**Comment by GlitchPlayer** [comment]
The plugin haven't yet implemented AI. It's on our readme
