### ISSUE TITLE
Pet plugin

### ISSUE THREAD

**Issue by dries-c** [thelucyclub/Pets#30]
https://github.com/Driesboy/LbCore/tree/master/src/Pets

**Comment by thelucyclub** [comment]
ur getting sued?

**Comment by jasonwynn10** [comment]
figures, LifeBoat didn't want their software public...

**Comment by thelucyclub** [comment]
then put it on MediaFire

**Comment by jasonwynn10** [comment]
Mediafire would probably slap him with a copyright too

**Comment by thelucyclub** [comment]
then send it to me [via email](mailto:thelucyclub@gmail.com)

**Comment by jasonwynn10** [comment]
I don't have it! look who made the issue post!

**Comment by GlitchPlayer** [comment]
So what is this about?

**Comment by Driesboy** [comment]
i have it

**Comment by Driesboy** [comment]
whats your mail i will send it

**Comment by thelucyclub** [comment]
[thelucyclub@gmail.com](mailto:thelucyclub@gmail.com&subject=LbCore%20Plugin)
Make sure subject is LbCore Plugin

**Comment by thelucyclub** [comment]
@Driesboy

**Comment by jasonwynn10** [comment]
send it to me too! jasonwynn10@gmail.com

**Comment by thelucyclub** [comment]
xD

**Comment by thelucyclub** [comment]
Dude I can have over 34000 players on my home XPS. You can have 15. xD

**Comment by jasonwynn10** [comment]
I only set it at 15, IDK what the max is

**Comment by thelucyclub** [comment]
https://github.com/LolYouDontKnowWhoIAm/LBCORE

**Comment by dries-c** [comment]
i can post it back

**Comment by jasonw4331** [comment]
do it under a different name
