### ISSUE TITLE
Can you stop adding me as a collaborator?

### ISSUE THREAD

**Issue by ifvictr** [thelucyclub/Pets#31]
You've added me to this repository as a collaborator **twice** now. When someone leaves a repository, that means that they do not want to contribute, or help. I'm leaving the repository now, if you re-add me, I'll delete everything in this repository. Some advice also: Think twice before adding someone to your repository/organization, you don't want to end up how **ImagicalMine** did now, do you? Take this warning seriously, it's not a joke, and I will do what I say.

**Comment by thelucyclub** [comment]
I will. And I know. I wrote like a 800-word web page about how much i hate [you know who](github.com/DALTONTASTIC). But I seriously trust you. I will stop I just thought I never added you in the first place.
